# Generated by Django 5.0 on 2024-03-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='parties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_no', models.CharField(max_length=100)),
                ('sponser', models.CharField(max_length=100)),
                ('Party_name', models.CharField(max_length=100)),
                ('Leader', models.CharField(max_length=100)),
            ],
        ),
    ]
