# Generated by Django 5.0 on 2024-03-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parties',
            old_name='party_no',
            new_name='Partie_no',
        ),
        migrations.AddField(
            model_name='parties',
            name='Partie_Email',
            field=models.EmailField(default='', max_length=200),
        ),
    ]
