# Generated by Django 5.0 on 2024-03-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('Sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Phone_no', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=200)),
            ],
        ),
    ]
