# Generated by Django 5.0 on 2024-03-23 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting_home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
