# Generated by Django 5.0 on 2024-03-23 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting_home', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Address',
            new_name='Content',
        ),
    ]
