# Generated by Django 5.0 on 2024-03-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_home', '0004_rename_address_contact_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Name',
            new_name='First_name',
        ),
        migrations.AddField(
            model_name='contact',
            name='Last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
