# Generated by Django 5.0 on 2024-03-23 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting_home', '0005_rename_name_contact_first_name_contact_last_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Feedback',
        ),
    ]
