# Generated by Django 5.0 on 2024-03-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('Adhar_no', models.BigIntegerField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=200)),
            ],
        ),
    ]
