# Generated by Django 5.0 on 2024-03-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registeration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='email_name',
            field=models.EmailField(default='', max_length=200),
        ),
    ]
