# Generated by Django 5.0 on 2024-03-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registeration', '0002_register_email_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='Last_name',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='Address',
            new_name='location',
        ),
        migrations.AddField(
            model_name='register',
            name='confim_password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
