# Generated by Django 5.0 on 2024-03-30 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registeration', '0003_rename_last_name_register_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='location',
        ),
    ]
