# Generated by Django 5.0 on 2024-03-30 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registeration', '0004_remove_register_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='confim_password',
            new_name='Confirm_Password',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='email_name',
            new_name='Email',
        ),
    ]
